### ISSUE TITLE
Incorrect "Read-Only" Warning in VSCode Plug-In

### ISSUE THREAD

**Issue by gregorycoppola** [hirosystems/clarinet#392] opened 2022-05-31 21:39 UTC
## Description of the error
![image](https://user-images.githubusercontent.com/60008382/171288624-2ff644fc-d35c-4a26-bfb8-301e30dd39f8.png)

I'm told I'm using a `writing operation` when creating a `define-read-only` function.

## Steps to Reproduce
* I opened the files `hyperchains.clar` from the `hirosystems/stacks-hyperchains` repo in VSCode with the Hiro clarinet plug-in
* I went to add a new `define-read-only` function.
* I get this warning

## Additional Notes
The actual clarinet test that calls this contracts runs fine. I even had the ts code print the value:

```
$ clarinet test
Running file:///home/greg/subnet6/core-contracts/tests/hyperchains/hyperchains_test.ts
{ count: { session_id: 1, result: "(ok 5)", events: [] } }
* Ensure that block can be committed by subnet miner ... ok (9ms)
* Ensure that user can deposit NFT & miner can withdraw it ... ok (58ms)
* Ensure that user can deposit FT & miner can withdraw it ... ok (66ms)

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (1024ms)
```

**Comment by obycode** [comment] 2022-06-01 13:26
I can't reproduce this. @gregorycoppola, do you get that error when you run `clarinet check` or only in VS Code? Which version of clarinet are you using?

**Comment by obycode** [comment] 2022-06-07 19:31
Is it possible that there was previously a writing operation on this line and the old error was not properly cleared? I think I have seen that happen before.

**Comment by lgalabru** [comment] 2022-10-06 11:18
@hugocaillard could we please test this snippet and close this issue if you're unable to reproduce?
Thanks!

**Comment by hugocaillard** [comment] 2022-10-06 12:07
Can't reproduce
Agreed with @obycode's previous message, what can happen is that the extensions crashes and previous diagnostics don't get cleaned up.
We fixed a few of the crashes root causes recently

**Closed by hugocaillard** 2022-10-06 12:07 UTC
Labels: bug
