### ISSUE TITLE
Billboard Example Error

### ISSUE THREAD

**Issue by javalight** [hirosystems/clarinet#259] opened 2022-02-13 22:31 UTC
clarinet check      
     
`error: Failed to lex input remainder: '
`
```
;; error consts
(define-constant ERR_STX_TRANSFER   u0)

;; data vars
(define-data-var billboard-message (string-utf8 500) u"Hello World!")
(define-data-var price uint u100)

;; public functions
(define-read-only (get-price)
    (var-get price)
)

(define-read-only (get-message)
    (var-get billboard-message)
)

(define-public (set-message (message (string-utf8 500)))
    (let ((cur-price (var-get price))
          (new-price (+ u10 cur-price)))

        ;; pay the contract
        (unwrap! (stx-transfer? cur-price tx-sender (as-contract tx-sender)) (err ERR_STX_TRANSFER))
        ;; update the billboard's message
        (var-set billboard-message message)

        ;; update the price of setting a message
        (var-set price new-price)

        ;; return the updated price
        (ok new-price)
    )
)
```
```
warning: conflict between parser versions, reverting to parser v1
Help improve clarinet by sharing the code that triggered this warning:
https://github.com/hirosystems/clarinet/issues/new/choose
```

The examples need updating

**Comment by obycode** [comment] 2022-02-15 20:50
Hi @javalight. I'm not seeing any error when I copy and paste this contract. Is there another contract in your project maybe that is causing this error.

**Comment by javalight** [comment] 2022-02-16 00:27
> 

Have you tried install the [billboard example app](https://github.com/hirosystems/stacks-billboard) and run clarinet check? 

[Contract](https://github.com/hirosystems/stacks-billboard/blob/main/contracts/billboard.clar)

**Comment by obycode** [comment] 2022-02-16 13:14
Yes, I don't see any errors from `clarinet check`. The only problem I had with the billboard example was that the version of postcss specified in the package.json was not compatible with the latest version of Node.js, which is fixed now (https://github.com/hirosystems/stacks-billboard/commit/6515713f237e0ac934622a3e878ed36ebf6ceb37).

Which version of clarinet are you using?

Here's my output:
```
➜  stacks-billboard git:(main) clarinet --version
clarinet 0.26.0

➜  stacks-billboard git:(main) clarinet check

✔ Syntax of 1 contract(s) successfully checked
```

**Comment by obycode** [comment] 2022-02-16 16:18
> Was using clarinet 0.26.1

Oops, I was actually using 0.26.1 as well, but had a local build without the version number updated. 0.26.1 is still recommended. 

> using windows os
That's interesting. I wonder if there are some characters in there that Windows doesn't like. Let me look into that...

**Comment by obycode** [comment] 2022-02-16 19:52
Ok, I was able to reproduce your problem by switching the line endings from LF to CRLF on my Mac. I think your editor changed the line-endings to the Windows style line-endings (CRLF), and the blockchain only accepts LF.

If you change that file to use `\n` (LF) for the end of lines, then `clarinet check` should work for you. You can do this in VS Code by opening this file, clicking the "CRLF" on the bottom bar, then selecting "LF" in the menu that pops up at the top and saving the file. If that works for you, please go ahead and close this issue.

_Side note: This actually caught a bug in the new parser v2, because it was accepting either line ending while the original parser failed (with a terrible error message). I'll create an issue to look for this in parser v2 and report a nice error._

**Comment by obycode** [comment] 2022-02-16 19:57
See https://github.com/hirosystems/clarity-repl/issues/98

**Comment by javalight** [comment] 2022-02-17 09:14
Nice! It all works! :)

**Closed** 2022-02-17 14:44 UTC
