### ISSUE TITLE
Error When Creating New Contracts

### ISSUE THREAD

**Issue by mcsuy1998** [hirosystems/clarinet#61] opened 2021-06-26 07:50 UTC
Action: 
clarinet new contract new counter

Result
Creating file contracts/counter.clar
thread 'main' panicked at 'Unable to create file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/frontend/cli.rs:545:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by LNow** [comment] 2021-06-26 14:32
Which version do you use? 
Please make sure that it's the latest one (v0.13.0).

**Comment by mcsuy1998** [comment] 2021-06-26 14:33
It should be v0.14.0.

**Comment by LNow** [comment] 2021-06-26 14:58
You're right. I missed v0.14.0 release and unfortunately it re-introduced back the problem that was fixed in v0.13.0

**Comment by MarvinJanssen** [comment] 2021-06-26 21:23
Looks like this is an ugly error you get when trying to do `clarinet contract new` in a non-Clarinet project folder.

Try this:
```bash
clarinet new my-project
cd my-project
clarinet contract new counter
```

**Comment by suleman-mahmood** [comment] 2021-06-27 11:41
Release: v0.14.0

Action:
clarinet new my-project
cd my-project
clarinet contract new my-contract

Result:
Creating file contracts/my-contract.clar
thread 'main' panicked at 'Unable to create file: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', src\frontend\cli.rs:545:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ZKhan007** [comment] 2021-06-28 08:35
Having the same error in release v0.14.0

**Comment by lgalabru** [comment] 2021-06-28 15:37
Probably a regression introduced with the manifest-file option, I'll have a look.

**Comment by lgalabru** [comment] 2021-06-28 20:48
Addressed in latest `main` branch

**Closed by lgalabru** 2021-06-28 20:48 UTC
