### ISSUE TITLE
File system completion for deployment plans

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#717] opened 2022-12-13 15:14 UTC
After typing `clarinet integrate -p ` or `clarinet deployments apply -p `, I should be able to tab-complete the path to the deployment plan file.

**Comment by hugocaillard** [comment] 2023-01-16 16:55
It seems to work on my end.
Also it's maybe my config (a pretty basic zsh / oh my zsh), everytime I press tab the path completion is triggered

**Comment by obycode** [comment] 2023-01-16 19:07
Ok, thanks for checking that. It might be a config problem on my end then. I also noticed recently that when doing a `diff`, I'm getting completion for the first file, but not for the second file.

**Comment by hugocaillard** [comment] 2023-01-25 14:39
I actually have the same behavior as you do for `diff`.

Anyway, closing this as can't reproduce.
Let me know if you find something strange in you're config @obycode 

@lgalabru could you give it a try before we close it?

**Closed** 2023-02-01 15:36 UTC
Labels: functional enhancement
