### ISSUE TITLE
Telemetry is enabled regardless of user input

### ISSUE THREAD

**Issue by erfanyeganegi** [hirosystems/clarinet#317] opened 2022-04-10 05:19 UTC
Creating a new project using the `clarinet new` command and not providing the `--disable-telemetry` option asks the user whether to enable telemetry or not. however, telemetry is enabled even if the user's input is `n`.

![screenshot](https://user-images.githubusercontent.com/76695726/162602621-e1832228-7609-4dfe-9743-4a7ba059a608.PNG)

**Comment by obycode** [comment] 2022-04-11 14:41
Thanks for reporting this @erfanyeganegi. This is an important bug. I think this may be a Windows problem caused by this check, `buffer != "n\n"`. I will test a fix for this now.

**Closed** 2022-04-12 21:27 UTC
Labels: bug, XS
