### ISSUE TITLE
aarch64 build and release

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#491] opened 2022-07-19 17:50 UTC
We identified that there is a problem with the current cross-compile build for aarch64 (for Apple silicon).

I think there are multiple phases to the solution for this:
1. Disable build and release for aarch64 in the CI jobs; manually build natively and upload the artifact to the release page
2. Fix the problem:
  a. Resolve the cross-compilation issue
  b. Configure the CI job to run natively on Apple silicon

I would say that properly fixing the problem is not urgent, since the manual solution is not difficult. I have added a note about the manual steps to our release playbook.

@CharlieC3 - Please add your thoughts on the CI side of this.

**Comment by CharlieC3** [comment] 2022-07-19 18:14
Option 1 seems like a good plan for the short-term.

Regarding option 2, do we happen to know what the root cause of the issue is? Are other people facing this same issue? There may a GH issue open for it we can track.

Additionally, we may be able to split the aarch64 build out to a separate CI platform that offers VMs running Apple silicon. I believe https://www.bitrise.io/ is an option, but there may be others to evaluate as well.

**Comment by obycode** [comment] 2022-07-20 17:47
No, I haven't spent much time yet to figure out the root cause. It appears that the JS engine is targeting the wrong architecture, but I'm not sure about that. It is entirely possible that the solution to fix the cross-compilation may be as simple as setting some environment variable.

**Comment by lgalabru** [comment] 2022-08-08 00:00
Could be addressed in https://github.com/hirosystems/clarinet/pull/511

**Comment by lgalabru** [comment] 2022-12-05 16:42
Issue still present as we speak (`v1.2.0`)

**Comment by smcclellan** [comment] 2024-06-18 19:56
@hugocaillard Is this one fixed?

**Comment by hugocaillard** [comment] 2024-06-18 20:33
Ah yes, that was the point of clarinet v2. We had a few duplicate issues about that.
Thanks for finding this one @smcclellan 🙌

**Closed by hugocaillard** 2024-06-18 20:33 UTC
Labels: bug, ci, icebox
