### ISSUE TITLE
How can I use LSP in neovim

### ISSUE THREAD

**Issue by Muizzyranking** [hirosystems/clarinet#1613] opened 2024-11-21 08:45 UTC
I have been trying to set up lsp for clarity in neovim and I can't get it to work. I have tried different method and none of it is working
this is what I currently have
```lua
{
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        clarity_lsp = {
          install_lsp = false, -- so it doesn't automatically install with mason
          cmd = { "clarinet", "lsp" },
          filetypes = { "clar", "clarity" },
          root_dir = require("lspconfig").util.root_pattern(".git", "Clarinet.toml"),
        },
      },
    },
  }
```
but it doesnt even show in the list of configured lsps when I run LspInfo. am i doing anything wrong?

**Comment by hugocaillard** [comment] 2024-11-21 13:45
Closing as duplicate of https://github.com/hirosystems/clarinet/discussions/1610

**Closed by hugocaillard** 2024-11-21 13:45 UTC
