### ISSUE TITLE
Check Checker should not report any warnings for `*-burn?`, `*-transfer?` operations

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#383] opened 2022-05-26 11:50 UTC
All operations listed below require `post-conditions` when transaction is created in `deny` mode, which means they are secured by `post-conditions` and should not be taken into account by `check-checker`.

- `stx-burn?`
- `stx-transfer?`
- `ft-burn?`
- `ft-transfer?`
- `nft-burn?`
- `nft-transfer?`

In my opinion there is no need to check/validate arguments of these functions if they are guarded by other mechanism. Therefore I'd like to ask you to either exempt them from `check-checker` or add an configuration option that can be used by developer to disable it manually.

**Comment by lgalabru** [comment] 2022-05-26 13:52
Filtering this functions by design might not be the right move, since they can be used for transferring assets on behalf of contracts, that can not be protected by post conditions.
There are a couple of knobs that you can use, described here: https://github.com/hirosystems/clarinet#check-checker

If you have some false positives that you'd like to see addressed, feel free to open an issues with snippets, so we can improve check-checker subtleties.

Thanks!

**Closed** 2022-05-26 13:53 UTC
